### ISSUE TITLE
Syncing with archived contact

### ISSUE THREAD

**Issue by PerfectSlayer** [antonplagemann/GoogleMonicaSync#59]
Hi @antonplagemann !

I have a quick question. I try to sync contacts from Google to Monica but I archived some in Monica.
So, they won't appear in contact list from Monica API and the interactive sync ask to recreate them at each run.

I wonder if:
1. You would like to support this case?
2. It would work if we query Monica API for the contact name (firstname / lastname) to try to find it if no other match was found?
3. If `__simple_monica_id_search(self, google_contact: dict) -> Union[str, None]` from `SyncHelper` is the right place to patch for this use case?

Best regards

**Comment by antonplagemann** [comment]
Hi @PerfectSlayer,

I'm sorry for the huge delay in my response. Thanks for opening this issue!
Let me directly answer your points:

1. Rather not, because I think this can be solved otherwise and I dont see a possible solution in the code yet (see 2.)
2. I looked up the documentation for the Monica API and couldnt find a request to query for archived contacts. So as of now it seems impossible to get them via the API (but I might have missed something).
3. My first thought is to just include archived contacts in the list of monica fetched contacts. I dont think they are read-only at Monica, so they can still synced. I would implement this in the `MonicaHelper.py` at `get_contacts` and `get_contact` if there were any possibility to get archived contacts via the API.

But I think we can solve this otherwise: You can exclude them from sync by simply creating a Google label (e.g. `archived`), applying it to your google contacts you archived at Monica and exclude those contacts from sync by adding them to the `GOOGLE_LABELS_EXCLUDE` variable in your config (e.g. `GOOGLE_LABELS_EXCLUDE=archived`).

I will close this issue for now as I am not seeing another solution. Feel free to answer and reopen it if necessary 😊
